name: Unit Test

on:
  pull_request:
    branches: [main]
      
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        
      - name: Use cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test
